### ISSUE TITLE
what about s2_geography fields?

### ISSUE THREAD

**Issue by erikarasnick** [cole-brokamp/dpkg#13]
https://github.com/cole-brokamp/dpkg/blob/8e1e115de43c09e56207008a4c286f695d53358f/R/read_write_dpkg.R#L65-L68

We started using `arrow` and `geoarrow` to write parquet files with `sfc` columns, but updated version of `addr` uses s2_geography type, which doesn't seem to work with this

**Comment by cole-brokamp** [comment]
I think converting to a `sfc` column using the `sf` package would be best approach.  I'm not sure if geoarrow supports s2 geographies in R, but keeping with simple features will make sure that it is the most interoperable once written to disk.
